sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t aniruddhand/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true aniruddhand/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "default"
  bucket_name: "elasticbeanstalk-us-east-1-981909225986"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $aws-access-key
  secret_access_key: "$aws-secret-key"